/obj/item/gravedecor
	name = "grave decoration"
	desc = "If you're seeing this, yell at coders."
	icon = 'icons/roguetown/items/graveitems.dmi'
	icon_state = "headstone_basic"
	gripped_intents = null
	possible_item_intents = list(INTENT_GENERIC)
	w_class = WEIGHT_CLASS_NORMAL
	resistance_flags = FIRE_PROOF
	/// This applies a gravequality bonus when added to a grave. 1 means a CHEAP decoration, usually wood. 2 means a MODERATE decoration, usually masoned stone.
	/// 3 means an EXPENSIVE decoration, usually forged.
	var/decorationquality
	/// Set this if this decoration is not crafted/doesn't have an item state, but instead is made by using a non decoration item on a grave. MUST BE TYPE
	var/sourceitem
	/// Patrons associated with this grave decoration. Usually a headstone.
	var/list/patrons

/obj/item/gravedecor/New(loc, var/parent)
	if(parent)
		sourceitem = parent
	. = ..()

/obj/item/gravedecor/headstone
	name = "peaked headstone"
	desc = "A headstone with a sharp peak, and plenty of room for an inscription."
	icon_state = "headstone_basic"
	decorationquality = 2

	/// Generated by burial_rites, what will be read on examine with grave or the headstone itself
	var/inscription
	/// Modified by by a chisel or short sharp object, allows for a small message to be added to inscription
	var/custom_message

/obj/item/gravedecor/headstone/examine(mob/user)
	. = ..()

	if(inscription)
		to_chat(user, inscription) //Should already be formatted
		to_chat(user, span_warning("Shouldn't this be attached to a grave?"))
	else if(custom_message) // Not inscribed, but there is a custom_message
		. += span_info("There is a message carved into the middle of \the [src]...")
		to_chat(user, span_italics("[custom_message]"))
	else if(!custom_message) // No custome message, send message that it can be done, they can change custom_message even if already set but we imply there is 'space'
		. += span_info("There appears to be space to inscribe a message, I can probably do this with a chisel or other short, sharp object...")

/obj/item/gravedecor/headstone/attackby(obj/item/I, mob/living/user, list/modifiers)
	if(istype(I, /obj/item/weapon/chisel) || (I.wlength == WLENGTH_SHORT)) // Chisel or dagger
		if(I.wlength == WLENGTH_SHORT && !(I.get_sharpness())) // If dagger but not sharp
			to_chat(user, span_warning("\The [I] is not sharp enough to engrave \the [src]!"))
			return

		var/new_message = tgui_input_text(user, "What would you like to be inscribed on \the [src]?", "Custom Inscription", custom_message, 150, TRUE)
		if(!new_message || new_message == custom_message)
			return

		user.visible_message(span_info("[user] begins to engrave a message into \the [src] with \a [I]."), span_info("You begin to engrave a message into \the [src]."), span_info("You hear someone cutting into stone."))
		playsound(src, pick('sound/combat/hits/onrock/onrock (1).ogg', 'sound/combat/hits/onrock/onrock (2).ogg', 'sound/combat/hits/onrock/onrock (3).ogg', 'sound/combat/hits/onrock/onrock (4).ogg'), 100)
		if(!do_after(user, 5 SECONDS, src, progress=TRUE, display_over_user=TRUE))
			return
		else
			user.visible_message(span_info("[user] finishes working on \the [src]."), span_info("You finish engraving \the [src] with your message."))
			custom_message = new_message
			return

	. = ..()


/obj/item/gravedecor/headstone/crude
	name = "crude headstone"
	desc = ""
	icon_state = "gravemarker1"
	sourceitem = /obj/item/grown/log/tree/stick
	decorationquality = 1

/obj/item/gravedecor/headstone/psydon
	name = "psydonic headstone"
	desc = "A psycross shaped headstone, may be considered heretical by some, but to disturb the graves it lies upon even more so."
	icon_state = "headstone_psydon"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/psydon, /datum/patron/psydon/extremist)

/obj/item/gravedecor/headstone/astrata
	name = "astratan headstone"
	desc = "The golden cross of Astrata, nothing less for the Sun Tyrant."
	icon_state = "headstone_astrata"
	dropshrink = 0.8
	decorationquality = 3
	patrons = list(/datum/patron/divine/astrata)

/obj/item/gravedecor/headstone/pestra
	name = "pestran headstone"
	desc = "Any grave this is on is practically begging to be robbed. Maybe that's the intent."
	icon_state = "headstone_pestra"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/pestra)

/obj/item/gravedecor/headstone/abyssor
	name = "abyssorite headstone"
	desc = "Not a common sight, most corpses are lost to his briny embrace before they can see land."
	icon_state = "headstone_abyssor"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/abyssor)

/obj/item/gravedecor/headstone/hunt
	name = "skull headstone"
	desc = "An uncommon sight in these lands, though it can barely be called a headstone, it is prestigious for those who earn it."
	icon_state = "headstone_hunt"
	dropshrink = 0.8
	decorationquality = 1
	patrons = list(/datum/patron/alternate/great_hunt, /datum/patron/alternate/great_hunt/proven)

/obj/item/gravedecor/headstone/necra
	name = "necran headstone"
	desc = "This one's time is up. Perhaps they never had any. Does it really matter?"
	icon_state = "headstone_necra"
	dropshrink = 0.8
	decorationquality = 2
	patrons = list(/datum/patron/divine/necra)

/obj/item/gravedecor/headstone/malum
	name = "malumite headstone"
	desc = "It's a toil to even install this."
	icon_state = "headstone_malum"
	dropshrink = 0.8
	decorationquality = 3
	patrons = list(/datum/patron/divine/malum)

/obj/item/gravedecor/gravefence
	name = "crude gravefence"
	desc = "A crude fence made of unshaped pebbles, made to deliniate a grave (somewhat) exactly."
	icon_state = "gravefence_stone"
	dropshrink = 0.8
	decorationquality = 1

/obj/item/gravedecor/gravefence/block
	name = "chiseled gravefence"
	desc = "A gravefence of blocks to be embedded in the earth, made to deliniate a grave exactly."
	icon_state = "gravefence_block"
	dropshrink = 0.8
	decorationquality = 2

/obj/item/gravedecor/gravefence/iron
	name = "iron gravefence"
	desc = "A wrought iron grave fence. Ominous."
	icon_state = "gravefence_iron"
	dropshrink = 0.8
	decorationquality = 3
