/// How much does devotion increase for quality above 7. This is also the minimum amount of devotion a 'T3' grave will generate
#define GRAVE_DEVOTION_INCREMENT 0.025
/// Absolute max passive devotion Necrans can get from all graves.
#define GRAVE_DEVOTION_GLOBAL_MAX 0.5

/obj/structure/closet/dirthole
	name = "hole"
	icon_state = "hole1"
	icon = 'icons/turf/floors.dmi'
	mob_storage_capacity = 3
	allow_dense = TRUE
	opened = TRUE
	density = FALSE
	anchored = TRUE
	can_buckle = FALSE
	resistance_flags = INDESTRUCTIBLE
	buckle_lying = 90
	layer = 2.8
	lock = null
	can_add_lock = FALSE
	alternative_icon_handling = TRUE
	/// How big the hole is, at 3 you can bury a body, at 4 theres something buried.
	var/stage = 1
	/// Chance for attempt to increase `stage` fails, while still spawning dirt. Increments each fail and is skipped once it reaches 3
	var/faildirt = 0

	/// Present headstone. If this is empty, there isnt one.
	var/obj/item/gravedecor/headstone/headstone
	/// Present gravefence. If this is empty, there isnt one.
	var/obj/item/gravedecor/gravefence/gravefence
	/// From 0-10. You shouldn't be able to get more than 10 quality. This is affected by the headstone, gravefence, location of burial, and if you used a winding sheet / coffin.
	var/gravequality = 0
	/// For debug/administrative purposes. Set this if you want it to apply next time we call update_quality.
	var/bonusquality = 0
	/// Has the "burial rites" miracle been used on this grave. TRUE or FALSE.
	var/is_consecrated = FALSE

	/// How much passive devotion is generated by this grave. Updated by `adjust_grave_necra_devotion()`
	var/necra_devotion_gain = 0
	/// If TRUE, no devotion is calculated for this dirthole. Useful for spawned bodies we don't want to count.
	var/no_devotion = FALSE

/obj/structure/closet/dirthole/Initialize()
	var/turf/open/floor/dirt/T = loc
	if(!istype(T))
		return INITIALIZE_HINT_QDEL
	if(T.muddy && stage != 4)
		if(!(locate(/obj/item/natural/worms) in T))
			if(prob(40))
				if(prob(10))
					new /obj/item/natural/worms/grub_silk(T)
				else
					new /obj/item/natural/worms/leech(T)
			else
				new /obj/item/natural/worms(T)
		if(!(locate(/obj/item/natural/clay) in T))
			if(prob(25))
				new /obj/item/natural/clay(T)
	else
		if(!(locate(/obj/item/natural/stone) in T))
			if(prob(23))
				new /obj/item/natural/stone(T)
	stage_update()
	return ..()

/obj/structure/closet/dirthole/Destroy()
	// Remove passive devotion
	is_consecrated = FALSE
	adjust_grave_necra_devotion()
	. = ..()

/obj/structure/closet/dirthole/examine(mob/user)
	if(headstone)
		if(headstone.inscription)
			to_chat(user, headstone.inscription) // We do it this way since dirthole doesnt have an examine usually, so we have it just displayed.
	if(is_consecrated)
		switch(gravequality)
			if(0 to 3)
				user.add_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(4 to 6)
				user.add_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(7 to 9)
				user.add_stress(/datum/stress_event/saw_grave_3)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_4)
			if(10)
				user.add_stress(/datum/stress_event/saw_grave_4)
				user.remove_stress(/datum/stress_event/saw_grave_1)
				user.remove_stress(/datum/stress_event/saw_grave_2)
				user.remove_stress(/datum/stress_event/saw_grave_3)

/obj/structure/closet/dirthole/grave
	stage = 3
	faildirt = 3
	icon_state = "grave"

/obj/structure/closet/dirthole/closed
	stage = 4
	faildirt = 3
	climb_offset = 10
	icon_state = "gravecovered"
	opened = FALSE

/// Right clicking with hand allows you to remove grave decorations if the grave has not been consecrated yet
/obj/structure/closet/dirthole/attack_hand_secondary(mob/user, list/modifiers)
	if(!Adjacent(user) || stage != 4)
		return FALSE

	if(is_consecrated)
		to_chat(user, span_warning("I cannot modify a grave that has been already consecrated..."))
		return FALSE

	var/list/grave_decorations = list()
	if(headstone)
		grave_decorations += headstone
	if(gravefence)
		grave_decorations += gravefence

	// List formed, handle if empty, only one, or both
	var/obj/item/gravedecor/item_to_remove
	if(!grave_decorations)
		return FALSE
	else if(length(grave_decorations) != 1)
		item_to_remove = tgui_input_list(user, "Which decoration do you want to remove?", "Grave Decor Removal", grave_decorations)
	else
		item_to_remove = grave_decorations[1] // only one item

	if(!item_to_remove)
		return FALSE

	// Time to actually remove the item
	user.visible_message(span_info("[user] starts to remove \the <span class='bold'>[item_to_remove]</span> from \the [src]"), span_notice("You attempt to remove \the <span class='bold'>[item_to_remove]</span> from \the [src]"))
	playsound(src, 'sound/items/dig_shovel.ogg', 100, FALSE)
	if(!do_after(user, 5 SECONDS, src, progress = TRUE))
		to_chat(user, span_warning("You fail to remove \the [item_to_remove]!"))
		return FALSE

	user.visible_message(span_info("[user] removes \the <span class='bold'>[item_to_remove]</span> from \the [src]"), span_notice("You remove \the <span class='bold'>[item_to_remove]</span> from \the [src]"))
	// Remove either headstone or gravestone
	if(istype(item_to_remove, /obj/item/gravedecor/headstone))
		if(item_to_remove.sourceitem)
			user.put_in_active_hand(new item_to_remove.sourceitem())
		else
			// We need to perserve custom_message and inscription
			var/obj/item/gravedecor/headstone/replacement = new item_to_remove.type()
			replacement.inscription = headstone.inscription
			replacement.custom_message = headstone.custom_message
			user.put_in_active_hand(replacement)
		headstone = null
	else if(istype(item_to_remove, /obj/item/gravedecor/gravefence))
		if(item_to_remove.sourceitem)
			user.put_in_active_hand(new item_to_remove.sourceitem())
		else
			user.put_in_active_hand(new item_to_remove.type())
		gravefence = null
	update_quality()
	update_appearance(UPDATE_ICON)
	return TRUE

/obj/structure/closet/dirthole/insertion_allowed(atom/movable/AM)
	if(istype(AM, /obj/structure/closet/crate/chest) || istype(AM, /obj/structure/closet/burial_shroud) || istype(AM, /obj/structure/closet/crate/coffin))
		for(var/mob/living/M in contents)
			return FALSE
		for(var/obj/structure/closet/C in contents)
			return FALSE
		return TRUE
	. = ..()

/obj/structure/closet/dirthole/toggle(mob/living/user)
	return

/obj/structure/closet/dirthole/proc/attemptwatermake(obj/item/reagent_containers/bucket, mob/living/user)
	if(user.used_intent.type == /datum/intent/splash)
		if(bucket.reagents)
			var/datum/reagent/master_reagent = bucket.reagents.get_master_reagent()
			var/reagent_volume = master_reagent.volume
			if(do_after(user, 10 SECONDS, src))
				if(bucket.reagents.remove_reagent(master_reagent.type, clamp(master_reagent.volume, 1, 100)))
					var/turf/structure_turf = get_turf(src)
					var/turf/open/water/W = structure_turf.PlaceOnTop(/turf/open/water/river/creatable)
					if(!W) // how did this happen
						return
					W.water_reagent = master_reagent.type
					W.water_volume = clamp(reagent_volume, 1, 100)
					W.handle_water()
					playsound(W, 'sound/foley/waterenter.ogg', 100, FALSE)
					QDEL_NULL(src)

/obj/structure/closet/dirthole/attackby(obj/item/attacking_item, mob/user, list/modifiers)
//If you want to add in more items that arent a gravedecor subtype but do have an associated gravedecoration, add them here.
//In the future, an associated list can be made between any non-gravedecor items, and their associated decoration. We only have one such case, so that isnt necessary.
	if(istype(attacking_item, /obj/item/grown/log/tree/stick))
		if(headstone)
			to_chat(user, "<span class='warning'>This grave already has a headstone.</span>")
			return
		if(stage != 4)
			to_chat(user, "<span class='warning'>I can't tie a grave marker on an open grave.</span>")

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 10 SECONDS, src))
			return
		//We're checking this istype twice in case any other headstone without the gravedecor path is added.
		if(istype(attacking_item, /obj/item/grown/log/tree/stick))
			headstone = new /obj/item/gravedecor/headstone/crude(parent = attacking_item.type)
		if(pacify_coffin(src, user))
			user.visible_message(span_rose("[user] consecrates [src]."), span_rose("I consecrate [src]."))
			if(!is_consecrated)
				SEND_SIGNAL(user, COMSIG_GRAVE_CONSECRATED, src)
				record_round_statistic(STATS_GRAVES_CONSECRATED)

		update_quality()
		update_appearance(UPDATE_ICON)
		qdel(attacking_item)
		return

	if(istype(attacking_item, /obj/item/gravedecor))
		attack_decor(attacking_item, user)
	else if(istype(attacking_item, /obj/item/weapon/shovel))
		attack_shovel(attacking_item, user)
	else if(istype(attacking_item, /obj/item/reagent_containers/glass/bucket))
		attemptwatermake(attacking_item, user)
	else
		return ..()

/// Called by `attackby()`, handles interactions with gravedecor objects
/obj/structure/closet/dirthole/proc/attack_decor(obj/item/gravedecor/attacking_item, mob/user)
	if(istype(attacking_item, /obj/item/gravedecor/headstone))
		if(headstone)
			to_chat(user, "<span class='warning'>This grave already has a headstone.</span>")
			return
		if(stage != 4)
			to_chat(user, "<span class='warning'>I can't put a headstone on an open grave.</span>")
			return

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 5 SECONDS, src))
			return

		headstone = attacking_item
		if(pacify_coffin(src, user))
			user.visible_message(span_rose("[user] consecrates [src]."), span_rose("I consecrate [src]."))
			if(!is_consecrated)
				SEND_SIGNAL(user, COMSIG_GRAVE_CONSECRATED, src)
				record_round_statistic(STATS_GRAVES_CONSECRATED)

		qdel(attacking_item)
		update_quality()
		update_appearance(UPDATE_ICON)
		return

	if(istype(attacking_item, /obj/item/gravedecor/gravefence))
		if(gravefence)
			to_chat(user, "<span class='warning'>This grave already has a fence.</span>")
			return
		if(stage != 4)
			to_chat(user, "<span class='warning'>I can't put a gravefence on an open grave.</span>")
			return

		playsound(src, 'sound/foley/bandage.ogg', 100, FALSE)
		if(!do_after(user, 5 SECONDS, src))
			return
		gravefence = attacking_item

		qdel(attacking_item)
		update_quality()
		update_appearance(UPDATE_ICON)
		return

/// Called by `attackby()`. Handles interactions with shovels.
/obj/structure/closet/dirthole/proc/attack_shovel(obj/item/weapon/shovel/attacking_shovel, mob/user)
	if(user.used_intent.type != /datum/intent/shovelscoop)
		return

	if(attacking_shovel.heldclod)
		playsound(src,'sound/items/empty_shovel.ogg', 100, TRUE)
		if(stage == 3) //close grave
			if(!do_after(user, 5 SECONDS * attacking_shovel.time_multiplier, src)) //can't have nice things can we
				return
			stage = 4
			climb_offset = 10
			close()
			update_quality()
			var/founds
			for(var/atom/A in contents)
				founds = TRUE
				break
			if(!founds)
				stage = 2
				climb_offset = 0
				open()
			stage_update()
		else if(stage < 4)
			stage--
			climb_offset = 0
			stage_update()
			if(stage == 0)
				qdel(src)
		QDEL_NULL(attacking_shovel.heldclod)
		attacking_shovel.update_appearance(UPDATE_ICON_STATE)
		return
	else
		if(stage == 3)
			var/turf/our_turf = get_turf(src)
			var/turf/under_turf = GET_TURF_BELOW(our_turf)
			if(under_turf && our_turf && isopenturf(under_turf))
				playsound(src,'sound/items/dig_shovel.ogg', 100, TRUE)
				user.visible_message("[user] starts digging out the bottom of [src]", "I start digging out the bottom of [src].")
				if(!do_after(user, 10 SECONDS * attacking_shovel.time_multiplier, src))
					return TRUE
				attacking_shovel.heldclod = new(attacking_shovel)
				attacking_shovel.update_appearance(UPDATE_ICON_STATE)
				playsound(our_turf,'sound/items/dig_shovel.ogg', 100, TRUE)
				our_turf.ScrapeAway(flags = CHANGETURF_INHERIT_AIR)
				qdel(src)
				return
			to_chat(user, "<span class='warning'>I think that's deep enough.</span>")
			return
		playsound(src,'sound/items/dig_shovel.ogg', 100, TRUE)
		var/used_str = 10
		if(iscarbon(user))
			var/mob/living/carbon/C = user
			if(C.domhand)
				used_str = C.get_str_arms(C.used_hand)
			C.adjust_stamina(max(60 - (used_str * 5), 1))
		if(stage < 3)
			if(faildirt < 2)
				if(prob(used_str * 5))
					stage++
				else
					faildirt++
			else
				stage++
		if(stage == 4)
			if(gravequality == 10 && !HAS_TRAIT(user, TRAIT_GRAVEROBBER)) // Are you sure you want to do this?
				to_chat(user, span_boldwarning("You feel a chill as you begin to dig at the grave, as if something <span class='god_necra'>ancient</span> is watching you... am you prepared to face the consequences if you continue?"))
			if(!do_after(user, 5 SECONDS * attacking_shovel.time_multiplier, src)) // WE CANT HAVE NICE THINGS CAN WE
				return
			stage = 3
			climb_offset = 0
			open()
			if(headstone)
				if(headstone.sourceitem)
					new headstone.sourceitem(get_turf(src))
				else
					// We need to perserve custom_message and inscription
					var/obj/item/gravedecor/headstone/replacement = new headstone.type(get_turf(src))
					replacement.inscription = headstone.inscription
					replacement.custom_message = headstone.custom_message
				headstone = null
			if(gravefence)
				if(gravefence.sourceitem)
					new gravefence.sourceitem(get_turf(src))
				else
					new gravefence.type(get_turf(src))
				gravefence = null
			if(is_consecrated)	// Curses you if you don't have the graverobber trait, otherwise records you as a criminal and gives a special message.
				if(ishuman(user))
					var/mob/living/carbon/human/L = user
					if(HAS_TRAIT(L, TRAIT_GRAVEROBBER))
						var/robbing = TRUE
						var/message = "I perform the secret rite of concealment, the Undermaiden won't know of my transgression here."
						switch(L.patron?.type)
							if(/datum/patron/divine/necra)
								robbing = FALSE
								message = "I perform the secret rite of exhumation, and so the Undermaiden overlooks my transgression."
							if(/datum/patron/divine/pestra) //Special notices if you're of a particular faith.
								message = "I perform the secret rite of concealment, Pestra shields me from divine gaze as I exhume this corpse for study."
							if(/datum/patron/inhumen/matthios)
								message = "I perform the secret rite of liberation, the Undermaiden is none the wiser as the occupant of this grave is freed."
							if(/datum/patron/inhumen/zizo)
								message = "I perform the secret rite of defilement, the Undermaiden can do nothing but watch as I undo the rites on this grave."
						to_chat(user, span_info(message))
						if(robbing)
							record_featured_stat(FEATURED_STATS_CRIMINALS, user) //You aren't a Necran, even though you didn't get any consequences you're still a criminal.
							record_round_statistic(STATS_GRAVES_ROBBED)
							SEND_SIGNAL(user, COMSIG_GRAVE_ROBBED, user)
							addtimer(CALLBACK(src, TYPE_PROC_REF(/obj/structure/closet/dirthole, robbery_alert), L), rand(20,90) SECONDS) // Delayed alert
					else
						//Logic thread for curses.
						switch(gravequality)
							if(0 to 3)
								L.visible_message("<span class='warning'>As [L] opens the grave, the stasis held on it breaks, releasing all the stored time!</span>", \
								"<span class='warning'>As soon as I dig up the grave, all the stored time within is released! I can feel myself age a little...</span>", \
								"<span class='hear'>I hear a loud whoosh!</span>")
								if(!L.has_status_effect(/datum/status_effect/debuff/cursed_t4) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t3) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t2))
									L.apply_status_effect(/datum/status_effect/debuff/cursed_t1)
							if(4 to 6)
								L.visible_message("<span class='warning'>As [L] opens the grave, the stasis held on it breaks, releasing all the stored time!</span>", \
								"<span class='warning'>As soon as I dig up the grave, all the stored time within is released! I feel myself age a few years...</span>", \
								"<span class='hear'>I hear a loud whoosh!</span>")
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
								if(!L.has_status_effect(/datum/status_effect/debuff/cursed_t4) && !L.has_status_effect(/datum/status_effect/debuff/cursed_t3))
									L.apply_status_effect(/datum/status_effect/debuff/cursed_t2)
							if(7 to 9)
								L.visible_message("<span class='warning'>As [L] opens the grave, the stasis held on it breaks, releasing all the stored time! \n\ [L] freezes in place, as whispers of alarm flutter out in every direction.</span>", \
								"<span class='warning'>As soon as I dig up the grave, all the stored time within is released! \n\ While it freezes me in place, I can hear whispers of alarm go out in every direction!</span>", \
								"<span class='hear'>I hear a loud whoosh, then a cacophony of whispers!</span>")
								var/turf/T = get_turf(src)
								new /obj/effect/timestop(T, 2, 5 SECONDS, null, MAGIC_RESISTANCE_HOLY)
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t2)
								if(!(L.has_status_effect(/datum/status_effect/debuff/cursed_t4)))
									L.apply_status_effect(/datum/status_effect/debuff/cursed_t3)
								robbery_alert() // Now the entire church knows what you done!
							if(10) // Max curse...
								var/obj/item/bodypart/left_arm = L.get_bodypart(BODY_ZONE_L_ARM)
								var/obj/item/bodypart/right_arm = L.get_bodypart(BODY_ZONE_R_ARM)
								if(((!left_arm || left_arm.skeletonized) && (!right_arm || right_arm.skeletonized)))
									L.visible_message("<span class='warning'>As [L] opens the grave, the stasis held on it breaks, releasing all the stored time! \n\ [L] freezes in place and whispers of alarm flutter out in every direction.</span>", \
									"<span class='warning'>As soon as I dig up the grave, all the stored time within is released! \n\ While it freezes me in place, I can feel my arms age as whispers of alarm go out in every direction!</span>", \
									"<span class='hear'>I hear a loud whoosh, then a cacophony of whispers!</span>")
								else
									L.visible_message("<span class='warning'>As [L] opens the grave, the stasis held on it breaks, releasing all the stored time! \n\ [L] freezes in place, as their arms wither to bone, and whispers of alarm flutter out in every direction.</span>", \
									"<span class='warning'>As soon as I dig up the grave, all the stored time within is released! </span>\n\ <span class='warning big'>While it freezes me in place, I can feel my arms wither to bone as whispers of alarm go out in every direction!</span>", \
									"<span class='hear'>I hear a loud whoosh, then a cacophony of whispers!</span>")
									if(left_arm)
										var/obj/item/bodypart/part_to_bonify = L.get_bodypart(BODY_ZONE_L_ARM)
										part_to_bonify.skeletonize(FALSE)
									if(right_arm)
										var/obj/item/bodypart/part_to_bonify = L.get_bodypart(BODY_ZONE_R_ARM)
										part_to_bonify.skeletonize(FALSE)
									L.emote("painscream")
									L.update_body_parts()
								var/turf/T = get_turf(src)
								new /obj/effect/timestop(T, 2, 15 SECONDS, null, MAGIC_RESISTANCE_HOLY)
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t1)
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t2)
								L.remove_status_effect(/datum/status_effect/debuff/cursed_t3)
								L.apply_status_effect(/datum/status_effect/debuff/cursed_t4)
								robbery_alert() // Now the entire church knows what you done!
						record_featured_stat(FEATURED_STATS_CRIMINALS, user)
						record_round_statistic(STATS_GRAVES_ROBBED)
						SEND_SIGNAL(user, COMSIG_GRAVE_ROBBED, user)

			unstasis() // if no longer stage 4, unfreeze the bodies

		stage_update()
		attacking_shovel.heldclod = new /obj/item/natural/clod/dirt(attacking_shovel)
		attacking_shovel.update_appearance(UPDATE_ICON_STATE)
		is_consecrated = FALSE // Unconsecrate.
		cut_overlays()
		update_quality()
		adjust_grave_necra_devotion()

/// Alerts all clergy (except non-necran acoyltes) of a robbery!
/obj/structure/closet/dirthole/proc/robbery_alert(mob/robber, var/delay = FALSE)
	var/robbery_location = get_area_name(get_turf(src))
	if(robber) // Graverobbers get a delay before the alert, to give them time to leave
		to_chat(robber, span_warning("The rites I performed on \the [src] have bought me time, but the whispers of the disturbed dead were eventually able to break through... I need to get out of here!!"))

	for (var/mob/living/player in GLOB.player_list)
		if (player.stat == DEAD || isbrain(player))
			continue
		if (is_priest_job(player.mind.assigned_role) || (is_monk_job(player.mind.assigned_role) && player.patron?.type == /datum/patron/divine/necra) || istype(player.mind.assigned_role, /datum/job/templar) || istype(player.mind.assigned_role, /datum/job/gmtemplar) || istype(player.mind.assigned_role, /datum/job/undertaker))
			to_chat(player, span_crit("Veiled whispers hiss of great blasphemy, a highly blessed grave is being robbed in [robbery_location], this cannot go unpunished!"))

/// All bodies buried as 'frozen' in time, Necra's gift to ensure their bodies cease to decay
/obj/structure/closet/dirthole/proc/stasis()
	for(var/mob/living/corpse in get_all_contents())
		if(corpse.stat == DEAD)
			ADD_TRAIT(corpse, TRAIT_STASIS, GRAVE_TRAIT)

/// Reverse of `statis()`
/obj/structure/closet/dirthole/proc/unstasis()
	for(var/mob/living/corpse in get_all_contents())
		if(corpse.stat == DEAD)
			REMOVE_TRAIT(corpse, TRAIT_STASIS, GRAVE_TRAIT)

/// Proc that looks for valid turf and puts a necran lily on it.
/obj/structure/closet/dirthole/proc/grow_lily()
	for(var/turf/foundturf in range(1, src))
		if(istype(foundturf, /turf/open/floor/dirt || /turf/open/floor/dirt/road || /turf/open/floor/grass)) //Turf the lily can grow on.
			if(!locate(/obj/structure) in foundturf)
				new /obj/structure/flora/grass/herb/necralily(foundturf)
				break

/obj/structure/closet/dirthole/MouseDrop_T(atom/movable/O, mob/living/user)
	var/turf/T = get_turf(src)
	if(istype(O, /obj/structure/closet/crate/coffin))
		O.forceMove(T)
	if(!istype(O) || O.anchored || istype(O, /atom/movable/screen))
		return
	if(!istype(user) || user.incapacitated() || user.body_position == LYING_DOWN)
		return
	if(!Adjacent(user) || !user.Adjacent(O))
		return
	if(user == O) //try to climb onto it
		return ..()
	if(!opened)
		return
	if(!isturf(O.loc))
		return

	var/actuallyismob = FALSE
	if(isliving(O))
		actuallyismob = TRUE
	else if(!isitem(O))
		return
	add_fingerprint(user)
	user.visible_message("<span class='warning'>[user] [actuallyismob ? "tries to ":""]stuff [O] into [src].</span>", \
						"<span class='warning'>I [actuallyismob ? "try to ":""]stuff [O] into [src].</span>", \
						"<span class='hear'>I hear clanging.</span>")
	if(actuallyismob)
		if(do_after(user, 4 SECONDS, O))
			user.visible_message("<span class='notice'>[user] stuffs [O] into [src].</span>", \
								"<span class='notice'>I stuff [O] into [src].</span>", \
								"<span class='hear'>I hear a loud bang.</span>")
			O.forceMove(T)
			user_buckle_mob(O, user)
	else
		O.forceMove(T)
	return 1

/obj/structure/closet/dirthole/take_contents()
	var/atom/L = drop_location()
	..()
	for(var/obj/structure/closet/crate/coffin/C in L)
		if(C != src && insert(C) == -1)
			break


/obj/structure/closet/dirthole/close(mob/living/user)
	if(!opened || !can_close(user))
		return FALSE
	take_contents()
	for(var/mob/A in contents)
		if((A.stat) && (istype(A, /mob/living/carbon/human)))
			var/mob/living/carbon/human/B = A
			B.buried = TRUE
	opened = FALSE
	return TRUE

/obj/structure/closet/dirthole/dump_contents()
	for(var/mob/A in contents)
		if((!A.stat) && (istype(A, /mob/living/carbon/human)))
			var/mob/living/carbon/human/B = A
			B.buried = FALSE
	..()

/obj/structure/closet/dirthole/open(mob/living/user)
	if(opened)
		return
	if(stage == 4)
		stage = 3
		climb_offset = 0
	opened = TRUE
	dump_contents()
	stage_update()
	return 1

/obj/structure/closet/dirthole/proc/stage_update()
	switch(stage)
		if(1, 2, 4)
			can_buckle = FALSE
		if(3)
			can_buckle = TRUE
	update_appearance(UPDATE_ICON | UPDATE_NAME)

/// Proc to update `quality`, should be called when `headstone` or `gravefence` is modified, and other cases where the condition of the grave has changed
/obj/structure/closet/dirthole/proc/update_quality()
	gravequality = 0
	if(stage != 4) // If not a complete grave, no quality
		return
	if(bonusquality)
		gravequality += bonusquality

	// Check if area is fit for burials
	var/area/A = get_area(src)
	if(A.burial_grounds)
		gravequality += 1

	// Calculate damage to buried bodies and provide malus if too damaged.
	var/bodyquality = 0
	for(var/mob/living/carbon/human/corpse in get_all_contents()) // We only care about humans
		// No head? -1 point
		if(!(corpse.get_bodypart(BODY_ZONE_HEAD)))
			bodyquality -= 1

		// Too much brute or burn damage? -1 point
		if(corpse.getBruteLoss() >= 75 || corpse.getFireLoss() >= 75)
			bodyquality -= 1

	gravequality += bodyquality

	if(headstone)
		var/headquality = headstone.decorationquality
		for(var/mob/living/corpse in contents)
			if(corpse.patron.type in headstone.patrons)
				headquality = 3
		gravequality += headquality

	if(gravefence)
		var/fencequality = gravefence.decorationquality
		for(var/mob/living/corpse in contents)
			if(corpse.patron.type in gravefence.patrons)
				fencequality = 3
		gravequality += fencequality
	for(var/obj/structure/closet/crate/coffin/coffin in contents)
		gravequality += 1
		if(coffin.consecrated)
			gravequality += 2
	for(var/obj/structure/closet/burial_shroud/shroud in contents)
		gravequality += 1

	gravequality = clamp(gravequality, 0, 10)
	adjust_grave_necra_devotion()
	return

/// Proc that adjusts every necran's devotion passive gain based on grave quality, up to global max
/obj/structure/closet/dirthole/proc/adjust_grave_necra_devotion()
	var/new_devotion = 0
	var/change = 0
	if(no_devotion)
		return

	// Step 1: Calculate new_devotion
	if(gravequality >= 7 && is_consecrated) // T3 and higher graves get devotion, otherwise is 0
		new_devotion = GRAVE_DEVOTION_INCREMENT * (gravequality - 6) // For each level of quality above 6, increment.

	// Step 2: Compare new_devotion with necra_devotion_gain to find change.
	change = new_devotion - necra_devotion_gain
	necra_devotion_gain = new_devotion

	if(change == 0) // Nothing to adjust
		return

	// Step 3: Implement change
	// Update potential devotion gain
	GLOB.potential_grave_devotion_gain += change

	// Adjust devotion gain for each gravetender, up to a max
	for (var/mob/living/carbon/human/player in GLOB.player_list)
		if (player.stat == DEAD || isbrain(player) || !player.cleric)
			continue
		if(player.patron?.type == /datum/patron/divine/necra) // Person must be able to use miracles and worship Necra
			// Grab their devotion
			var/datum/devotion/devotion = player.cleric
			var/current_passive_gain = devotion.passive_devotion_gain
			var/devotion_change = change

			if(current_passive_gain == GRAVE_DEVOTION_GLOBAL_MAX && GLOB.potential_grave_devotion_gain < GRAVE_DEVOTION_GLOBAL_MAX) // At max and we are not reducing it, skip
				continue

			// We grab the potential_grave_devotion_gain and have each gravetender update to reach it (or stopped by max)
			// potential_grave_devotion_gain is less than max
			if(GLOB.potential_grave_devotion_gain <= GRAVE_DEVOTION_GLOBAL_MAX)
				devotion_change = GLOB.potential_grave_devotion_gain - current_passive_gain // Have their devotion generation match potential_grave_devotion_gain by calculating the difference and adding/decreasing

			else // potential_grave_devotion_gain is over MAX, have devotion set to max
				devotion_change = GRAVE_DEVOTION_GLOBAL_MAX - current_passive_gain

			devotion.update_passive_devotion(devotion_change)
	return

/obj/structure/closet/dirthole/update_icon_state()
	. = ..()
	switch(stage)
		if(1)
			icon_state = "hole1"
		if(2)
			icon_state = "hole2"
		if(3)
			icon_state = "grave"
		if(4)
			icon_state = "gravecovered"

/obj/structure/closet/dirthole/update_overlays()
	. = ..()
	if(stage < 3)
		return
	else if(stage == 3)
		. += mutable_appearance(icon, "grave_above", ABOVE_MOB_LAYER)

	if(is_consecrated)
		switch(gravequality)
			if(0 to 3)
				. += mutable_appearance('icons/turf/floors.dmi', "consecration1", 2.92)
			if(4 to 6)
				. += mutable_appearance('icons/turf/floors.dmi', "consecration2", 2.92)
			if(7 to 9)
				. += mutable_appearance('icons/turf/floors.dmi', "consecration3", 2.92)
			if(10)
				. += mutable_appearance('icons/turf/floors.dmi', "consecration4", 2.92)
	if(headstone)
		. += mutable_appearance('icons/turf/floors.dmi', headstone.icon_state, 2.91)
	if(gravefence)
		. += mutable_appearance('icons/turf/floors.dmi', gravefence.icon_state, 2.9)

/obj/structure/closet/dirthole/update_name(updates)
	. = ..()
	switch(stage)
		if(1, 2)
			name = "hole"
		if(3)
			name = "pit"
		if(4)
			name = "grave"

/obj/structure/closet/dirthole/post_buckle_mob(mob/living/M)
	. = ..()
	update_appearance(UPDATE_OVERLAYS)

/obj/structure/closet/dirthole/post_unbuckle_mob()
	. = ..()
	update_appearance(UPDATE_OVERLAYS)

/obj/structure/closet/dirthole/relaymove(mob/user)
	if(user.stat || !isturf(loc) || !isliving(user))
		return
	if(!user.mind?.has_antag_datum(/datum/antagonist/zombie))
		if(message_cooldown <= world.time)
			message_cooldown = world.time + 50
			to_chat(user, "<span class='warning'>I'm trapped!</span>")
		return
	container_resist(user)

#undef GRAVE_DEVOTION_INCREMENT
#undef GRAVE_DEVOTION_GLOBAL_MAX
